rootProject.name = "dzinner"
include(":account")
include(":data")
include(":bot")
include(":co_bot")
include(":account-ui")
include(":report")
include(":ai")
include(":solaris")
include(":web-client")
include(":account-fe")
include(":web-client")
include("account-lite")
